import { QuestionData } from '../types/benchmark';

export const QUESTIONS_DATA: QuestionData[] = [
  {
    key: 'P1',
    field: 'p1',
    category: 'VISIBILIDAD CROSS-LAYER',
    question: '¿Tienes herramientas para monitorear energía, cooling y workloads?',
    descriptions: {
      1: 'No tenemos herramientas de monitoreo; todo se revisa manualmente o no se revisa.',
      2: 'Tenemos herramientas básicas solo para una de las capas (ej. solo energía).',
      3: 'Monitoreamos 2 de las 3 capas con herramientas independientes.',
      4: 'Monitoreamos las 3 capas, pero con herramientas separadas y sin integración.',
      5: 'Monitoreamos energía, cooling y workloads con herramientas integradas en tiempo real.',
    },
  },
  {
    key: 'P2',
    field: 'p2',
    category: 'VISIBILIDAD CROSS-LAYER',
    question: '¿Tienes dashboards que unifiquen las 3 capas?',
    descriptions: {
      1: 'No tenemos dashboards; los datos se consultan manualmente si es necesario.',
      2: 'Tenemos dashboards básicos para una sola capa.',
      3: 'Tenemos dashboards separados para cada capa, sin correlación entre ellos.',
      4: 'Tenemos dashboards que combinan 2 capas con cierta correlación.',
      5: 'Tenemos un dashboard unificado que correlaciona energía, cooling y workloads en tiempo real.',
    },
  },
  {
    key: 'P3',
    field: 'p3',
    category: 'VISIBILIDAD CROSS-LAYER',
    question: '¿Qué tan detallada es tu telemetría?',
    descriptions: {
      1: 'No recopilamos datos de telemetría.',
      2: 'Recopilamos métricas básicas (ej. temperatura ambiente, consumo total) con poca frecuencia.',
      3: 'Telemetría moderada: métricas clave por zona con actualizaciones periódicas.',
      4: 'Telemetría detallada por rack/equipo con actualizaciones cada pocos minutos.',
      5: 'Telemetría granular a nivel de servidor/componente con datos en tiempo real e incluye Scope 1-2-3.',
    },
  },
  {
    key: 'P4',
    field: 'p4',
    category: 'ATRIBUCIÓN DE FRICCIÓN',
    question: '¿Qué tan sincronizados están energía y workload?',
    descriptions: {
      1: 'No hay coordinación; energía y workloads operan de forma totalmente independiente.',
      2: 'Coordinación mínima; se ajusta energía solo en emergencias o fallas.',
      3: 'Coordinación reactiva; se hacen ajustes de energía después de que cambian los workloads.',
      4: 'Coordinación proactiva; energía se ajusta anticipándose a cambios de carga planificados.',
      5: 'Sincronización en tiempo real; el sistema de energía se adapta automáticamente a la demanda de workloads.',
    },
  },
  {
    key: 'P5',
    field: 'p5',
    category: 'ATRIBUCIÓN DE FRICCIÓN',
    question: '¿Qué tan sincronizados están cooling y workload?',
    descriptions: {
      1: 'No hay coordinación; el cooling opera con configuración fija sin importar la carga.',
      2: 'Coordinación mínima; se ajusta cooling solo ante alertas de temperatura crítica.',
      3: 'Coordinación reactiva; se ajusta cooling después de detectar cambios térmicos.',
      4: 'Coordinación proactiva; cooling se pre-ajusta según la carga esperada.',
      5: 'Sincronización en tiempo real; el cooling se adapta dinámicamente a la carga térmica real de los workloads.',
    },
  },
  {
    key: 'P6',
    field: 'p6',
    category: 'LATENCIA DE COORDINACIÓN',
    question: '¿Cuánto tarda la coordinación MANUAL entre teams?',
    descriptions: {
      1: 'Semanas: requiere reuniones, aprobaciones y tickets entre múltiples equipos.',
      2: 'Días: hay procesos definidos pero lentos, con dependencias entre equipos.',
      3: 'Horas: los equipos se comunican el mismo día, pero con fricción en la coordinación.',
      4: 'Menos de una hora: hay canales directos y procesos ágiles entre equipos.',
      5: 'Minutos: los equipos están co-ubicados o tienen protocolos de respuesta inmediata.',
    },
  },
  {
    key: 'P7',
    field: 'p7',
    category: 'LATENCIA DE COORDINACIÓN',
    question: '¿Tienes semi-automatización?',
    descriptions: {
      1: 'Todo es 100% manual; no hay automatización en ningún proceso operativo.',
      2: 'Automatización mínima; solo alertas automáticas, las acciones son manuales.',
      3: 'Algunos procesos tienen scripts o runbooks semi-automáticos que requieren aprobación manual.',
      4: 'La mayoría de procesos rutinarios están semi-automatizados con supervisión humana.',
      5: 'Automatización avanzada con intervención humana solo para decisiones críticas o excepciones.',
    },
  },
  {
    key: 'P8',
    field: 'p8',
    category: 'LATENCIA DE COORDINACIÓN',
    question: '¿Tienes automatización completa?',
    descriptions: {
      1: 'No hay automatización completa en ningún proceso.',
      2: 'Solo tareas triviales están automatizadas (ej. backups, rotación de logs).',
      3: 'Algunos flujos de provisioning o scaling tienen automatización end-to-end.',
      4: 'La mayoría de operaciones rutinarias están completamente automatizadas con auto-remediación.',
      5: 'Orquestación completa: provisioning, scaling, failover y optimización de recursos son 100% automáticos.',
    },
  },
  {
    key: 'P9',
    field: 'p9',
    category: 'AUTO-CUANTIFICACIÓN',
    question: '¿Cuantificas tu PUE (Power Usage Effectiveness)?',
    descriptions: {
      1: 'No medimos ni conocemos nuestro PUE.',
      2: 'Estimamos el PUE de forma aproximada, sin medición formal.',
      3: 'Medimos el PUE periódicamente (mensual o trimestral) con datos parciales.',
      4: 'Medimos el PUE continuamente y lo comparamos con benchmarks de la industria.',
      5: 'Medimos PUE en tiempo real por zona/sala, con metas de optimización activas y tracking de tendencias.',
    },
  },
  {
    key: 'P10',
    field: 'p10',
    category: 'AUTO-CUANTIFICACIÓN',
    question: '¿Sabes exactamente tu utilización real?',
    descriptions: {
      1: 'No medimos la utilización; desconocemos cuánta capacidad se usa realmente.',
      2: 'Tenemos una idea general pero sin datos concretos ni métricas formales.',
      3: 'Medimos utilización de CPU/memoria a nivel general, pero no identificamos capacidad desperdiciada.',
      4: 'Medimos utilización por servidor/rack y conocemos nuestra capacidad ociosa.',
      5: 'Medición granular en tiempo real con identificación precisa de stranded capacity y costos asociados.',
    },
  },
  {
    key: 'P11',
    field: 'p11',
    category: 'BLOQUEANTES',
    question: '¿Tienes suficiente personal calificado?',
    descriptions: {
      1: 'Déficit crítico; no cubrimos las necesidades mínimas de operación.',
      2: 'Personal insuficiente; dependemos de contratistas externos para operaciones básicas.',
      3: 'Personal suficiente para operaciones normales, pero sin capacidad para proyectos de mejora.',
      4: 'Personal adecuado con capacidad para operaciones y algunos proyectos de innovación.',
      5: 'Equipo completo y especializado, con capacidad para operar, innovar y formar talento.',
    },
  },
  {
    key: 'P12',
    field: 'p12',
    category: 'BLOQUEANTES',
    question: '¿Hay retrasos en cadena de suministro?',
    descriptions: {
      1: 'Retrasos severos (+6 meses); afectan la operación y expansión frecuentemente.',
      2: 'Retrasos significativos (3-6 meses); impactan la planificación de capacidad.',
      3: 'Retrasos moderados (1-3 meses); manejables pero requieren planificación anticipada.',
      4: 'Retrasos menores (<1 mes); rara vez impactan las operaciones.',
      5: 'Sin retrasos relevantes; cadena de suministro diversificada y con stock de respaldo.',
    },
  },
  {
    key: 'P13',
    field: 'p13',
    category: 'BLOQUEANTES',
    question: '¿Hay restricciones de la red eléctrica?',
    descriptions: {
      1: 'Restricciones severas; la red limita la operación actual y no hay alternativas.',
      2: 'Restricciones significativas; hay cortes frecuentes o límites de capacidad cercanos.',
      3: 'Restricciones moderadas; la red es estable pero sin margen para crecimiento.',
      4: 'Pocas restricciones; red estable con margen de crecimiento razonable.',
      5: 'Sin restricciones; red eléctrica confiable con capacidad amplia y/o fuentes renovables propias.',
    },
  },
  {
    key: 'P14',
    field: 'p14',
    category: 'BLOQUEANTES',
    question: '¿Hay restricciones regulatorias?',
    descriptions: {
      1: 'Restricciones severas que bloquean expansión o requieren cambios operativos mayores.',
      2: 'Restricciones significativas que limitan opciones de crecimiento o tecnología.',
      3: 'Restricciones moderadas; cumplimos la normativa pero limita algunas decisiones.',
      4: 'Pocas restricciones; la regulación es clara y no impide nuestros planes.',
      5: 'Entorno regulatorio favorable; las normativas apoyan nuestra operación y expansión.',
    },
  },
  {
    key: 'P15',
    field: 'p15',
    category: 'BLOQUEANTES',
    question: '¿Tienes expertise interna sólida?',
    descriptions: {
      1: 'No hay expertise especializado; dependemos completamente de proveedores externos.',
      2: 'Expertise básico; el equipo maneja operaciones rutinarias pero no puede resolver problemas complejos.',
      3: 'Expertise moderado; el equipo resuelve la mayoría de problemas pero necesita apoyo externo para temas avanzados.',
      4: 'Expertise sólido; el equipo maneja temas avanzados con apoyo externo solo en casos excepcionales.',
      5: 'Expertise completo; el equipo lidera innovación, capacita a otros y no depende de apoyo externo.',
    },
  },
];
